files: '^(src/|resource/|qmanager/|t/python/.*\.py|t/scripts/.*\.py)'
exclude: "^(src/bindings/python/_flux/|src/common/yggdrasil|src/bindings/python/flux/utils/|t/python/tap)"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.4
    hooks:
      - id: clang-format
        types_or: [c++, c]
